### PR TITLE
Microverse Portfolio Milestone 06

### PR DESCRIPTION
**Pull request by Titus-Kiplagat**
**Portfolio: accessibility**
- [x] Page titles - No issues found.
- [x] Image text alternatives - Found some issues (changed 'alt text' for both the GitHub icon and Scroll icon in the headline section).
- [x] Text headings - No issues found.
- [x] Color contrast - No issues found.
- [x] Resize - No issues found.
- [x] Interaction - Found some issues (Added labels to the form input fields in the contact section).
- [x] Moving content - No issues found.
- [x] Multimedia - No issues found.
- [x] The basic structure of the page - No issues found.

### CODE REVIEW

**Review by tugsem — CHANGES_REQUESTED** [review]
##  STATUS: REQUIRED CHANGES ♻️
Hello @Titus-Kiplagat  and @AliRezaBmeDu  👋 , 

Good job so far! 👏 
There are some issues that you still need to work on to go to the next project but you are almost there!

Alt Text
## Highlights 🚀 
✔️accessibility report is mostly positive
## Required Changes ♻️
As I couldn't highlight the code I am sending you the screenshots of the line that need to be changed: 
- [ ] Since your title isn't very adequate, please change it to 'Your name's Portfolio' or 'Your name full stack developer'.
image

- [ ] Kindly correct the contrast ratio of these 3 elements that are failing to make your website more readable by others who might have a lack of visual efficiency. You can use[ this website](https://www.aditus.io/button-contrast-checker/titus-kiplagat-github-io-2023-06-20-at-16-59-05-288?failing) to check them.
image

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by jerryowusu — APPROVED** [review]
Hi @Team
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


chelsea-mason-approve

## Highlights
Made requested changes :+1: 
Nice and positive reports :+1: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by AliRezaBmeDu — COMMENTED** [review]
The code is clear and working fine. Great Work! 👏

**Comment by mhassa204** [comment]
Good job! It seems to have no issue.:+1:

**Comment by BiancaMe** [comment]
Great initiative! Removing the unnecessary unordered list and replacing it with anchor tags inside the nav tags will not only improve the code's cleanliness but also enhance the semantic structure of the navigation section. This change will make the markup more intuitive, maintainable, and compliant with best practices. Please ensure to update the styling and accessibility attributes accordingly and thoroughly test the changes to ensure seamless navigation functionality. Well done!

**Pull request merged**
